language: node_js
node_js:
  - "12"
script:
  - ./bin/generate users -l 300 -o ./output
  # - echo 'dsti.adaltas.cloud' > output/CNAME
  # - pwd
  # - ls -l ./output
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: false
  local-dir: output
  on:
    branch: master
env:
  global:
  - secure: "dbo1YIFvEcaWRIKjyZ5hXmGqb1kCjJYhwCxAAHsNslZ7taSswARrBAOg02aKavHIPRladrGsodRBLFJ1q/+x/KxY6LgPyTkcQ7/lPK/awV/mMKzWTN1G9w+aF0FH4Ixu+I1Rn16dslOv6Bnz5w/jaWwiNy05Oo8HhzXDu0PRkPbhc+m+DuT/LkboxQrPGxfQ3ZSchaTg5FFOY/uhXhGod2wbaau+be0t4mP2rsmytqirdTBCWrx2kNpmgcG6urUUXdP3xSLe2obprDGsth9G9RaJqXyA561bt1bSPHNuX411+tQuvZ2qaTTEBr47zOIUofsDHGcyrySmFoEXKKdcNop6YIhcVFUIyNd69yqbLbeo7lUr9VPh+S15f3lii1MUmMWQNme6SgFe0L1mqlaFUD8tYAi9q7waMVMTZPLwxJWlFRRn5jdzxjcJ+UzPi3TCCjIU3lUJ3jVjtt8viOIWIDswzmj3kcAhX7eVtF02hku+10mG6qGVNFuWI9qJ7+ur9F0/4n/QqsH3lJR6GglizdOB7DTVbhReO/rOfbyQcRfbaUJ6lf5CgHdfd2GdvrLZge2MWvbaFi90ShziB7hAGV2aCQ8UEipVuYKApnjHUTum3EuAfJzFhrwMA2zzqFY1uaViG6Fd7LO/4/eX2AGnsxODi1M8gHMoaiGTr4fxwPE="
